/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malong_ainetdetect_JniCls */

#ifndef _Included_com_malong_ainetdetect_JniCls
#define _Included_com_malong_ainetdetect_JniCls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malong_ainetdetect_JniCls
 * Method:    init
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_malong_ainetdetect_JniCls_init(JNIEnv* env, jobject self,
                                                               jstring model_path, jint net_inp_width,
                                                               jint net_inp_height, jint net_inp_channel);

/*
 * Class:     com_malong_ainetdetect_JniCls
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_malong_ainetdetect_JniCls_destory(JNIEnv* env, jobject self);

/*
 * Class:     com_malong_ainetdetect_JniCls
 * Method:    run
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_malong_ainetdetect_JniCls_run(JNIEnv* env, jobject self, jobject bitmap);

/*
 * Class:     com_malong_ainetdetect_JniCls
 * Method:    get
 * Signature: ()Lcom/malong/ainetdetect/ClsInfo;
 */
JNIEXPORT jobject JNICALL Java_com_malong_ainetdetect_JniCls_get(JNIEnv* env, jobject self);

#ifdef __cplusplus
}
#endif
#endif
